In [1]:
import sys
# Define relative path.
sys.path.append("python")

In [2]:
import numpy as np

from sampling_trajectory import morris_trajectory
from screening_measures_gm_2017 import screening_measures_gm_2017

In [3]:
seed = 2020
n_levels = 10
n_inputs = 3
n_traj_sample = 10_000

sample_traj_list = list()

for traj in range(0, n_traj_sample):
    seed = seed + traj
    sample_traj_list.append(morris_trajectory(n_inputs, n_levels, seed=seed))

In [4]:
mu = np.array([0, 0, 0])
cov = np.array(
    [
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ]
)

In [5]:
def linear_function(a, b, c, *args):
    return a + b + c

In [6]:
abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures_gm_2017(linear_function, sample_traj_list, cov, n_levels, mu)

In [7]:
abs_ee_ind

array([[3.50972666],
       [3.52452796],
       [3.52326976]])

In [8]:
abs_ee_full

array([[3.50972666],
       [3.52452796],
       [3.52326976]])

In [9]:
sd_ee_ind

array([[3.59029975],
       [3.60507224],
       [3.6044974 ]])

In [10]:
sd_ee_full

array([[3.59029975],
       [3.60507224],
       [3.6044974 ]])

In [11]:
"""Ishigami"""
def ishigami(q0, q1, q2, a=2, b=3):
    """Note: Originally, this function takes uniform, not standard distributed inputs"""
    return np.sin(q0) + a*(np.sin(q1))**2 + b*q2**4*np.sin(q0)

In [12]:
a=2
b=3
vals = [0.5 + (a**2)/8 + (b*(np.pi**4))/5 + ((b**2)*(np.pi**8)/18),
        (0.5 + b*(np.pi**4)/5 + (b**2)*(np.pi**8)/50), (a**2)/8,
         0, 0, (8*b**2*np.pi**8)/225, 0, 0]
total_order = [(vals[1]+vals[5])/vals[0], vals[2]/vals[0], vals[5]/vals[0]]

In [13]:
total_order

[0.9998959138041636, 0.00010408619583630811, 0.6320800624240672]

In [14]:
abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures_gm_2017(ishigami, sample_traj_list, cov, n_levels, mu)

In [15]:
abs_ee_ind

array([[42.59704294],
       [ 1.76245653],
       [40.42377131]])

In [16]:
abs_ee_full

array([[42.59704294],
       [ 1.76245653],
       [40.42377131]])

In [17]:
sd_ee_ind

array([[86.33383537],
       [ 1.99044726],
       [65.83338771]])

In [18]:
sd_ee_full

array([[86.33383537],
       [ 1.99044726],
       [65.83338771]])

In [19]:
"""
new experiment, see on page 15 in
http://www2.stat.duke.edu/~fei/samsi/Readings/06LinkBingHengHigfYe.pdf

"""
seed = 2020
n_levels = 10
n_inputs = 8
n_traj_sample = 10_000

sample_traj_list = list()

for traj in range(0, n_traj_sample):
    seed = seed + traj
    sample_traj_list.append(morris_trajectory(n_inputs, n_levels, seed=seed))

In [20]:
def linkletter_et_al_2006(x0, x1, x2, x3, x4, x5, x6, x7, *args):
    epsilon = np.random.normal(0, 0.05)
    return 0.2*x0 + (0.2/2)*x1 + (0.2/4)*x2 + (0.2/8)*x3 + (0.2/16)*x4 + (0.2/32)*x5 + (0.2/64)*x6 + (0.2/128)*x7 + epsilon

In [21]:
mu = np.array([0, 0, 0, 0, 0, 0, 0, 0])


cov = np.array(
    [
        [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    ]
)

In [22]:
abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures_gm_2017(linkletter_et_al_2006, sample_traj_list, cov, n_levels, mu)

In [23]:
abs_ee_ind

array([[0.70474382],
       [0.35193499],
       [0.18727794],
       [0.12516729],
       [0.10707425],
       [0.10230089],
       [0.10064304],
       [0.10086744]])

In [24]:
abs_ee_full

array([[0.7022313 ],
       [0.3511954 ],
       [0.18676472],
       [0.12689746],
       [0.10747011],
       [0.10313151],
       [0.10258541],
       [0.10090118]])

In [25]:
sd_ee_ind

array([[0.73194562],
       [0.3815767 ],
       [0.22031387],
       [0.15502691],
       [0.13459269],
       [0.12849871],
       [0.12621347],
       [0.12637138]])

In [26]:
sd_ee_full

array([[0.72949032],
       [0.38054013],
       [0.22091247],
       [0.15691968],
       [0.13500733],
       [0.12893697],
       [0.12802605],
       [0.12648393]])