In [1]:
import sys
# Define relative path.
sys.path.append("python")

In [2]:
import numpy as np

from sampling_trajectory import morris_trajectory
from screening_measures_gm_2017 import screening_measures_gm_2017

In [3]:
seed = 2020
n_levels = 10
n_inputs = 3
n_traj_sample = 10_000

sample_traj_list = list()

for traj in range(0, n_traj_sample):
    seed = seed + traj
    sample_traj_list.append(morris_trajectory(n_inputs, n_levels, seed=seed))

In [11]:
mu = np.array([0, 0, 0])
cov = np.array(
    [
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ]
)

In [12]:
def linear_function(a, b, c, *args):
    return a + b + c

In [13]:
abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures_gm_2017(linear_function, sample_traj_list, cov, n_levels, mu)

In [14]:
abs_ee_ind

array([[3.27876643],
       [3.33920433],
       [3.51680064]])

In [15]:
abs_ee_full

array([[5.27560658],
       [5.27269679],
       [4.40978966]])

In [16]:
sd_ee_ind

array([[3.3718714 ],
       [3.80837096],
       [3.59757073]])

In [17]:
sd_ee_full

array([[5.39666771],
       [5.41093536],
       [4.78336579]])

In [ ]:
"""
new experiment, see on page 15 in
http://www2.stat.duke.edu/~fei/samsi/Readings/06LinkBingHengHigfYe.pdf

"""
seed = 2020
n_levels = 10
n_inputs = 8
n_traj_sample = 10_000

sample_traj_list = list()

for traj in range(0, n_traj_sample):
    seed = seed + traj
    sample_traj_list.append(morris_trajectory(n_inputs, n_levels, seed=seed))

In [27]:
def linkletter_et_al_2006(x0, x1, x2, x3, x4, x5, x6, x7, *args):
    epsilon = np.random.normal(0, 0.05)
    return 0.2*x0 + (0.2/2)*x1 + (0.2/4)*x2 + (0.2/8)*x3 + (0.2/16)*x4 + (0.2/32)*x5 + (0.2/64)*x6 + (0.2/128)*x7 + epsilon

In [28]:
mu = np.array([0, 0, 0, 0, 0, 0, 0, 0])


cov = np.array(
    [
        [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
    ]
)

In [29]:
abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures_gm_2017(linkletter_et_al_2006, sample_traj_list, cov, n_levels, mu)

In [30]:
abs_ee_ind

array([[0.7033641 ],
       [0.35312619],
       [0.18794998],
       [0.12725107],
       [0.10766467],
       [0.10247127],
       [0.10072058],
       [0.10078867]])

In [31]:
abs_ee_full

array([[0.70195692],
       [0.35109054],
       [0.18671375],
       [0.12750075],
       [0.10775441],
       [0.10327977],
       [0.10261925],
       [0.10088588]])

In [32]:
sd_ee_ind

array([[0.73023863],
       [0.38259265],
       [0.22079965],
       [0.15738223],
       [0.13520874],
       [0.12867584],
       [0.12630043],
       [0.12632719]])

In [33]:
sd_ee_full

array([[0.72959565],
       [0.38037356],
       [0.22012908],
       [0.1573466 ],
       [0.13493065],
       [0.12892774],
       [0.12809836],
       [0.12640902]])