In [1]:
import sys
# Define relative path.
sys.path.append("..")

In [2]:
import itertools
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from scrypy.sampling_schemes import trajectory_sample
from scrypy.sampling_schemes import radial_sample
from scrypy.screening_measures import screening_measures

In [3]:
"""Perhaps I need to add the scaled Elementary Effects (by SD)"""

'Perhaps I need to add the scaled Elementary Effects (by SD)'

In [4]:
def bar_plot(input_par_array):
    new_list = input_par_array.reshape(-1, 1).tolist()
    merged = pd.Series(itertools.chain.from_iterable(new_list))
    vc = merged.value_counts().sort_index()
    vc /= float(vc.sum())
    assert vc.sum() > 0.999
    ax = vc.plot(kind='bar')
    fig = ax.get_figure()
    fig.autofmt_xdate()

In [5]:
"""Example from Ge/Menendez (2017)"""
def linear_function(a, b, c, *args):
    return a + b + c

mu = np.array([0, 0, 0])
"""
cov = np.array(
    [
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ]
)
"""

cov = np.array(
    [
        [1.0, 0.9, 0.4],
        [0.9, 1.0, 0.01],
        [0.4, 0.01, 1.0],
    ]
)
n_inputs = 3
n_sample = 10_0

# Trajectory-specific paramters.
seed = 2020
n_levels = 10
n_inputs = 3


#traj_list, step_list = trajectory_sample(n_sample, n_inputs, n_levels, seed, True, numeric_zero)
traj_list, step_list = radial_sample(n_sample, n_inputs, normal=True)

In [6]:
"Check: For some even n_levels 1.0 has double the number of observations."
#bar_plot(np.vstack(traj_list))

'Check: For some even n_levels 1.0 has double the number of observations.'

In [7]:
"""I am able to replicate the results for the two normally distributed examples. The only difference is the scale because they seem to use another number of levels."""
#ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, traj_list, step_list, cov, mu, radial=False)
measures_list, _ = screening_measures(linear_function, traj_list, step_list, cov, mu, radial = True)

ee_uncorr = measures_list[0]
ee_corr = measures_list[1]
abs_ee_uncorr = measures_list[2]
abs_ee_corr = measures_list[3]
sd_ee_uncorr = measures_list[4]
sd_ee_corr = measures_list[5]

In [8]:
ee_uncorr

array([[1.],
       [1.],
       [1.]])

In [9]:
abs_ee_uncorr #last element is largest because it has the lowest correlation.

array([[1.],
       [1.],
       [1.]])

In [10]:
sd_ee_uncorr

array([[1.21421047e-15],
       [7.14238494e-15],
       [6.92533594e-16]])

In [11]:
ee_corr

array([[2.3 ],
       [1.91],
       [1.41]])

In [12]:
abs_ee_corr

array([[2.3 ],
       [1.91],
       [1.41]])

In [13]:
sd_ee_corr

array([[7.25647748e-16],
       [3.61394222e-15],
       [5.16939679e-16]])