In [1]:
import sys
# Define relative path.
sys.path.append("..")

In [2]:
import numpy as np

from scrypy.sampling_schemes import radial_sample
from scrypy.screening_measures import screening_measures

In [3]:
"""Test Case 1 from Ge/Menendez (2017)"""

"""Trajectory design"""

def linear_function(a, b, c, *args):
    return a + b + c

n_inputs = 3
n_rad = 10_000

mu = np.array([0, 0, 0])

cov = np.array(
    [
        [1.0, 0.9, 0.4],
        [0.9, 1.0, 0.01],
        [0.4, 0.01, 1.0],
    ]
)

In [4]:
"""SDs are a bit more distant from GM17 because their sample is too small and the SD is more sensitive to this."""   

'SDs are a bit more distant from GM17 because their sample is too small and the SD is more sensitive to this.'

In [5]:
rad_list, step_list = radial_sample(n_rad, n_inputs, True)

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, rad_list, step_list, cov, mu, radial=True)

In [6]:
abs_ee_ind

array([[0.57304553],
       [0.85476645],
       [1.31456479]])

In [7]:
abs_ee_full

array([[6.84239743],
       [7.76843475],
       [4.19460389]])

In [8]:
sd_ee_ind

array([[0.09596842],
       [0.40523434],
       [0.21988184]])

In [9]:
sd_ee_full

array([[1.14590203],
       [3.68292006],
       [0.70161412]])

In [10]:
"""Test Case 2"""

'Test Case 2'

In [11]:
cov = np.array(
    [
        [1.0, -0.9, -0.4],
        [-0.9, 1.0, 0.01],
        [-0.4, 0.01, 1.0],
    ]
)

In [12]:
"""SDs are a bit more distant from GM17 because their sample is too small and the SD is more sensitive to this."""   

'SDs are a bit more distant from GM17 because their sample is too small and the SD is more sensitive to this.'

In [13]:
rad_list, step_list = radial_sample(n_rad, n_inputs, True)

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, rad_list, step_list, cov, mu, radial=True)

In [14]:
abs_ee_ind

array([[0.57304553],
       [0.85476645],
       [1.31456479]])

In [15]:
abs_ee_full

array([[0.89248662],
       [0.44739677],
       [1.81468679]])

In [16]:
sd_ee_ind

array([[0.09596842],
       [0.40523434],
       [0.21988184]])

In [17]:
sd_ee_full

array([[0.14946548],
       [0.21210534],
       [0.30353519]])