In [1]:
import sys
# Define relative path.
sys.path.append("..")

In [2]:
import numpy as np

from scrypy.sampling_schemes import morris_trajectory
from scrypy.screening_measures import screening_measures

In [3]:
"""Test Case 1 from Ge/Menendez (2017)"""

"""Trajectory design"""

def linear_function(a, b, c, *args):
    return a + b + c

seed = 187
n_inputs = 3
n_traj_sample = 10_000

mu = np.array([0, 0, 0])

cov = np.array(
    [
        [1.0, 0.9, 0.4],
        [0.9, 1.0, 0.0],
        [0.4, 0.0, 1.0],
    ]
)

In [4]:
"""Replicate EEs with approx 7% deviations"""   
# Numerical paramteters taken from email by author Qiao Ge.
n_levels = 4
numeric_zero = 0.00001

In [5]:
traj_list = list()
step_list = list()
for traj in range(0, n_traj_sample):
    seed = seed + traj
    m_traj, step = morris_trajectory(n_inputs, n_levels, seed, True, numeric_zero)
    traj_list.append(m_traj)
    step_list.append(step)
    

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [6]:
abs_ee_ind

array([[1.21995737],
       [1.33108261],
       [2.79877415]])

In [7]:
abs_ee_full

array([[16.19988242],
       [13.38251157],
       [ 9.860798  ]])

In [8]:
sd_ee_ind

array([[1.32151083e-13],
       [1.43765809e-13],
       [3.02458227e-13]])

In [9]:
sd_ee_full

array([[1.75126000e-12],
       [1.44672027e-12],
       [1.06632363e-12]])

"""
SDs are almost zero because the inverse cdf is approximated linearly by the too coarse `numerical_zero` and especially the too coarse `n_levels`
see https://en.wikipedia.org/wiki/Quantile_function#/media/File:Probit_plot.png.
"""

In [10]:
"""Try out more "precise" parametrization."""
numeric_zero = 1e-8
n_levels = 24

In [11]:
"""Replicate SDs with some relatively small deviations"""
traj_list = list()
step_list = list()
for traj in range(0, n_traj_sample):
    seed = seed + traj
    m_traj, step = morris_trajectory(n_inputs, n_levels, seed, True, numeric_zero)
    traj_list.append(m_traj)
    step_list.append(step)


ee_ind_, ee_full_, abs_ee_ind_, abs_ee_full_, sd_ee_ind_, sd_ee_full_ = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [12]:
abs_ee_ind_

array([[0.7526802 ],
       [0.82062167],
       [1.71512417]])

In [13]:
abs_ee_full_

array([[9.9948827 ],
       [8.25041122],
       [6.04282164]])

In [14]:
sd_ee_ind_

array([[0.51004265],
       [0.55488893],
       [1.15798969]])

In [15]:
sd_ee_full_

array([[6.77288507],
       [5.57877282],
       [4.07989421]])

In [16]:
"""Conclusion: Radial is better for non-uniform paramters because the more dense coverage of the value space gets more import in case of non-linear cdfs."""

'Conclusion: Radial is better for non-uniform paramters because the more dense coverage of the value space gets more import in case of non-linear cdfs.'

In [31]:
"""Test Case 2"""

'Test Case 2'

In [18]:
cov = np.array(
    [
        [1.0, -0.9, -0.4],
        [-0.9, 1.0, 0.0],
        [-0.4, 0.0, 1.0],
    ]
)

In [19]:
"""Replicate EEs with approx 7% deviations"""   
# Numerical paramteters taken from email by author Qiao Ge.
n_levels = 4
numeric_zero = 0.00001

In [20]:
traj_list = list()
step_list = list()
for traj in range(0, n_traj_sample):
    seed = seed + traj
    m_traj, step = morris_trajectory(n_inputs, n_levels, seed, True, numeric_zero)
    traj_list.append(m_traj)
    step_list.append(step)
    

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [21]:
abs_ee_ind

array([[1.21995737],
       [1.33108261],
       [2.79877415]])

In [22]:
abs_ee_full

array([[2.11302814],
       [0.70434271],
       [4.22605628]])

In [23]:
sd_ee_ind

array([[1.31997691e-13],
       [1.43812989e-13],
       [3.02457854e-13]])

In [24]:
sd_ee_full

array([[2.28360776e-13],
       [7.63507452e-14],
       [4.56905009e-13]])

In [50]:
"""Try out more "precise" parametrization."""
numeric_zero = 1e-12
n_levels = 30

In [51]:
"""Replicate SDs with some relatively small deviations"""
traj_list = list()
step_list = list()
for traj in range(0, n_traj_sample):
    seed = seed + traj
    m_traj, step = morris_trajectory(n_inputs, n_levels, seed, True, numeric_zero)
    traj_list.append(m_traj)
    step_list.append(step)


ee_ind_, ee_full_, abs_ee_ind_, abs_ee_full_, sd_ee_ind_, sd_ee_full_ = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [52]:
abs_ee_ind_

array([[0.78652811],
       [0.84542102],
       [1.76626656]])

In [53]:
abs_ee_full_

array([[1.36230665],
       [0.44735476],
       [2.66700401]])

In [54]:
sd_ee_ind_

array([[0.64147867],
       [0.68749013],
       [1.43027347]])

In [55]:
sd_ee_full_

array([[1.11107365],
       [0.36378558],
       [2.15966558]])