In [1]:
import sys
# Define relative path.
sys.path.append("..")

In [2]:
import numpy as np

from scrypy.sampling_schemes import trajectory_sample
from scrypy.screening_measures import screening_measures

In [3]:
"""Test Case 1 from Ge/Menendez (2017)"""

"""Trajectory design"""

def linear_function(a, b, c, *args):
    return a + b + c

seed = 187
n_inputs = 3
n_traj = 10_000

mu = np.array([0, 0, 0])

cov = np.array(
    [
        [1.0, 0.9, 0.4],
        [0.9, 1.0, 0.01],
        [0.4, 0.01, 1.0],
    ]
)

In [4]:
"""Replicate EEs with approx 7% deviations"""   
# Numerical paramteters taken from email by author Qiao Ge.
n_levels = 4
numeric_zero = 0.00001

In [5]:
traj_list, step_list = trajectory_sample(n_traj, n_inputs, n_levels, seed, True, numeric_zero)

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [6]:
abs_ee_ind

array([[1.35672772],
       [1.48023728],
       [3.11239121]])

In [7]:
abs_ee_full

array([[16.19988242],
       [13.45294584],
       [ 9.93123227]])

In [8]:
sd_ee_ind

array([[1.46413993e-13],
       [1.59997419e-13],
       [3.36646492e-13]])

In [9]:
sd_ee_full

array([[1.75131033e-12],
       [1.45453856e-12],
       [1.07361574e-12]])

In [10]:
"""Important note below."""

'Important note below.'


SDs are almost zero because the inverse cdf is approximated linearly by the too coarse `numerical_zero` and especially the too coarse `n_levels`
see https://en.wikipedia.org/wiki/Quantile_function#/media/File:Probit_plot.png.

The precise problem for this case with n_levels = 4 is the following:
n_levels results in a value grid [0, 1/3, 2/3, 1] and step = 2/3. Given that the inverse cdf is point symmetric to (0.5, 0), the cdf does not introduce a non-linear difference between f(grid + step) - f(grid). In other words, a jump from 0 to 2/3 is equals to a jump from 1/3 to one if evaluated by inverse cdf (linearily approximated) and the linear function.


In [11]:
"""Replicate SDs with some relatively small deviations"""

"""Try out more "precise" parametrization."""
numeric_zero = 1e-8
n_levels = 24

In [12]:
traj_list, step_list = trajectory_sample(n_traj, n_inputs, n_levels, seed, True, numeric_zero)

ee_ind_, ee_full_, abs_ee_ind_, abs_ee_full_, sd_ee_ind_, sd_ee_full_ = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [13]:
abs_ee_ind_

array([[0.83479216],
       [0.91489299],
       [1.93711657]])

In [14]:
abs_ee_full_

array([[9.96775898],
       [8.31488711],
       [6.18108498]])

In [15]:
sd_ee_ind_

array([[0.56452964],
       [0.61994833],
       [1.31653401]])

In [16]:
sd_ee_full_

array([[6.74071427],
       [5.63432051],
       [4.20088741]])

In [17]:
"""Conclusion: Radial is better for non-uniform paramters because the more dense coverage of the value space gets more import in case of non-linear cdfs."""

'Conclusion: Radial is better for non-uniform paramters because the more dense coverage of the value space gets more import in case of non-linear cdfs.'

In [18]:
"""Test Case 2"""

'Test Case 2'

In [19]:
cov = np.array(
    [
        [1.0, -0.9, -0.4],
        [-0.9, 1.0, 0.01],
        [-0.4, 0.01, 1.0],
    ]
)

In [20]:
"""Replicate EEs with approx 7% deviations"""   
# Numerical paramteters taken from email by author Qiao Ge.
n_levels = 4
numeric_zero = 0.00001

In [21]:
traj_list, step_list = trajectory_sample(n_traj, n_inputs, n_levels, seed, True, numeric_zero)

ee_ind, ee_full, abs_ee_ind, abs_ee_full, sd_ee_ind, sd_ee_full = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [22]:
abs_ee_ind

array([[1.35672772],
       [1.48023728],
       [3.11239121]])

In [23]:
abs_ee_full

array([[2.11302814],
       [0.77477699],
       [4.29649056]])

In [24]:
sd_ee_ind

array([[1.46665521e-13],
       [1.60062860e-13],
       [3.36630415e-13]])

In [25]:
sd_ee_full

array([[2.28233002e-13],
       [8.37037553e-14],
       [4.64590751e-13]])

In [26]:
"""Replicate SDs with some relatively small deviations"""

"""Try out more "precise" parametrization."""
numeric_zero = 1e-12
n_levels = 30

In [27]:
traj_list, step_list = trajectory_sample(n_traj, n_inputs, n_levels, seed, True, numeric_zero)

ee_ind_, ee_full_, abs_ee_ind_, abs_ee_full_, sd_ee_ind_, sd_ee_full_ = screening_measures(linear_function, traj_list, step_list, cov, mu)

In [28]:
abs_ee_ind_

array([[0.86601733],
       [0.94021823],
       [1.99414729]])

In [29]:
abs_ee_full_

array([[1.34877394],
       [0.49212343],
       [2.75281429]])

In [30]:
sd_ee_ind_

array([[0.70504084],
       [0.76391663],
       [1.62591856]])

In [31]:
sd_ee_full_

array([[1.09806198],
       [0.3998447 ],
       [2.24449411]])